default['LAMP']['httpd_conf']['dir'] = '/etc/httpd/conf.d/'
default['LAMP']['httpd_conf']['name'] = 'virtual.conf'
default['LAMP']['vhost_domain'] = 'lamp.monosense.com'
default['LAMP']['www'] = '/var/www/'
default['LAMP']['doc_root'] = '/var/www/html/'
default['LAMP']['group']['name'] = 'www'
default['LAMP']['timezone'] = 'Asia/Tokyo'
