name 'LAMP'
maintainer 'Yuya'
maintainer_email 'maemichi@monosense.co.jp'
license 'all_rights'
description 'Installs/Configures LAMP'
long_description 'Installs/Configures LAMP'
version '0.5.0'

depends 'apache2', '~> 3.2.2'
depends 'mysql', '~> 7.2.0'
depends 'php', '~> 1.9.0'
depends 'php5-mysql', '~> 0.1.0'
