name 'LAMP'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures LAMP'
long_description 'Installs/Configures LAMP'
version '0.1.0'

depends 'apache2', '~> 3.2.2'
depends 'mysql', '~> 7.2.0'
depends 'php', '~> 1.9.0'
depends 'php5-mysql', '~> 0.1.0'
